name: adapti_flow
description: >-
  A comprehensive zero-dependency Flutter responsive design system with adaptive
  layouts, percentage-based sizing, device detection, design-proportional scaling,
  and fully customizable breakpoints. Works on all platforms.
version: 1.0.0

homepage: https://github.com/Md-LatifurRatul/Adapti-Flow
repository: https://github.com/Md-LatifurRatul/Adapti-Flow
issue_tracker: https://github.com/Md-LatifurRatul/Adapti-Flow/issues

environment:
  sdk: ^3.10.3
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
